In [31]:
import numpy as np

In [45]:
vector = np.array([1,2,3,4])
vector2 = np.array([4,3,2,1])

np.add(vector, vector2)

array([5, 5, 5, 5])

In [33]:
vector.shape

(4,)

In [40]:
matrix = np.array([[1, 2, 3],  [4, 5, 6], [7, 8, 9]])

print matrix

matrix.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [41]:
array = np.array([[1, 2, 3, 4, 5, 6, 7, 8], 
                  [8, 7, 6, 5, 4, 3, 2, 1], 
                  [0, 2, 4, 6, 8, 10, 12, 14], 
                  [1, 3, 5, 7, 9, 11, 13, 15]])
print array

array.shape

[[ 1  2  3  4  5  6  7  8]
 [ 8  7  6  5  4  3  2  1]
 [ 0  2  4  6  8 10 12 14]
 [ 1  3  5  7  9 11 13 15]]


(4, 8)

In [46]:
a = [1, 2, 3, 4, 5, 6]
b = [-6, -5, -4, -3, -2, -1]

np.add(a, b)

array([-5, -3, -1,  1,  3,  5])

In [47]:
c = [-1, -2, -3, -4, -5, -6]
d = [-6, -5, -4, -3, -2, -1]

np.subtract(c, d)

array([ 5,  3,  1, -1, -3, -5])

In [48]:
e = [101, 201, 33.22, -423, 5.3234, -6.234]
f = [-601, 501.33, -113, 3.3000003, -2, -1.999999999999999]

np.subtract(e, f)

array([ 702.       , -300.33     ,  146.22     , -426.3000003,
          7.3234   ,   -4.234    ])

In [93]:
g = np.array([-101, -201, -33.22, 423, -5.3234, -34])
h = np.array([601, -501.33, 113, -3.3000003, 'l', 10.999999999999999])

print h

[-101.     -201.      -33.22    423.       -5.3234  -34.    ]
['601' '-501.33' '113' '-3.3000003' 'l' '11.0']


In [97]:
g = [-101, -201, -33.22, 423, -5.3234, -34]
h = [601, -501.33, 113, -3.3000003, 'l', 10.999999999999999]

for i in range(len(h)):
    if type(h[i]) == str:
        h[i] = 0

print h

[601, -501.33, 113, -3.3000003, 0, 10.999999999999998]


In [53]:
x = [1, 2]
y = [2, 1]

np.dot(x, y)

4

In [77]:
array1 = np.array([0, 1, 2, 3, 5, 8])
array2 = np.array([1, 4, 9, 16, 25, 36])

print np.add(array1, array2)
print np.subtract(array1, array2)
print np.dot(array1, array2)

array_3d = np.array([[[0,1,2],[1,2,3]],[[2,1,0],[3,2,1]]])
array_5d = np.array([[[[[[1,2],[2,1]],[[0,1],[1,0]]],[[1,2],[2,1]],[[0,1],[1,0]]],
                     [[[[1,2],[2,1]],[[0,1],[1,0]]],[[1,2],[2,1]],[[0,1],[1,0]]]]])

print array_3d

print array_5d

print array_3d.shape
print array_5d.shape

[ 1  5 11 19 30 44]
[ -1  -3  -7 -13 -20 -28]
483
[[[0 1 2]
  [1 2 3]]

 [[2 1 0]
  [3 2 1]]]
[[[[[[1, 2] [2, 1]]
    [[0, 1] [1, 0]]]

   [[1 2]
    [2 1]]

   [[0 1]
    [1 0]]]


  [[[[1, 2] [2, 1]]
    [[0, 1] [1, 0]]]

   [[1 2]
    [2 1]]

   [[0 1]
    [1 0]]]]]
(2, 2, 3)
(1, 2, 3, 2, 2)
